<a href="https://colab.research.google.com/github/rachakondasaivarshini/DS-EXPS/blob/main/DS_EXP_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

# Create employee performance dataset
data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Age": [25, 30, 28, 35, 40, 26, 32, 29, 38, 45],
    "Department": [
        "IT", "HR", "Finance", "IT", "HR",
        "Finance", "IT", "HR", "Finance", "IT"
    ],
    "Gender": [
        "Male", "Female", "Female", "Male", "Female",
        "Male", "Male", "Female", "Male", "Female"
    ],
    "Salary": [35000, 45000, 40000, 60000, 55000,
               38000, 50000, 42000, 65000, 70000],
    "Performance_Score": [78, 85, 82, 90, 88, 75, 92, 80, 95, 89],
    "Experience": [2, 5, 4, 8, 10, 3, 7, 5, 12, 15]
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Save as CSV
df.to_csv("employee_performance.csv", index=False)

# Display the dataset
print("employee_performance.csv created successfully!")
display(df)

employee_performance.csv created successfully!

   Employee_ID  Age Department  Gender  Salary  Performance_Score  Experience
0          101   25         IT    Male   35000                 78           2
1          102   30         HR  Female   45000                 85           5
2          103   28    Finance  Female   40000                 82           4
3          104   35         IT    Male   60000                 90           8
4          105   40         HR  Female   55000                 88          10
5          106   26    Finance    Male   38000                 75           3
6          107   32         IT    Male   50000                 92           7
7          108   29         HR  Female   42000                 80           5
8          109   38    Finance    Male   65000                 95          12
9          110   45         IT  Female   70000                 89          15

In [3]:
import pandas as pd

# Load the dataset
df = pd.read_csv("employee_performance.csv")

# Display first 5 records
print("First 5 Records:")
display(df.head())

# Display structure
print("\nDataset Information:")
df.info()

# Display shape
print("\nShape of Dataset:")
print(df.shape)

# Display data types
print("\nData Types:")
print(df.dtypes)

# Identify numerical attributes
numerical_attributes = df.select_dtypes(
    include=["int64", "float64"]
).columns

# Identify categorical attributes
categorical_attributes = df.select_dtypes(
    include=["object", "category"]
).columns

print("\nNumerical Attributes:")
print(list(numerical_attributes))

print("\nCategorical Attributes:")
print(list(categorical_attributes))

First 5 Records:

   Employee_ID  Age Department  Gender  Salary  Performance_Score  Experience
0          101   25         IT    Male   35000                 78           2
1          102   30         HR  Female   45000                 85           5
2          103   28    Finance  Female   40000                 82           4
3          104   35         IT    Male   60000                 90           8
4          105   40         HR  Female   55000                 88          10

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        10 non-null     int64
 1   Age                10 non-null     int64
 2   Department         10 non-null     object
 3   Gender             10 non-null     object
 4   Salary             10 non-null     int64
 5   Performance_Score  10 non-null     int64
 6   Experience         10 non-null     int64
dtypes: int64(5), object(2)
memory usage: 692.0+ bytes

Shape of Dataset:
(10, 7)

Data Types:
Employee_ID           int64
Age                   int64
Department           object
Gender               object
Salary                int64
Performance_Score     int64
Experience            int64
dtype: object

Numerical Attributes:
['Employee_ID', 'Age', 'Salary', 'Performance_Score', 'Experience']

Categorical Attributes:
['Department', 'Gender']

In [4]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Load the dataset
df = pd.read_csv("employee_performance.csv")

# Select numerical attributes for Min-Max Scaling
features = ["Age", "Experience", "Salary"]

# Create Min-Max Scaler
scaler = MinMaxScaler()

# Perform Min-Max Scaling
df[features] = scaler.fit_transform(df[features])

# Display the transformed dataset
print("Dataset after Min-Max Scaling:")
display(df)

Dataset after Min-Max Scaling:

,Employee_ID,Age,Department,Gender,Salary,Performance_Score,Experience
0,101,0.00,IT,Male,0.000000,78,0.000000
1,102,0.25,HR,Female,0.285714,85,0.230769
2,103,0.15,Finance,Female,0.142857,82,0.153846
3,104,0.50,IT,Male,0.714286,90,0.461538
4,105,0.75,HR,Female,0.571429,88,0.615385
5,106,0.05,Finance,Male,0.085714,75,0.076923
6,107,0.35,IT,Male,0.428571,92,0.384615
7,108,0.20,HR,Female,0.200000,80,0.230769
8,109,0.65,Finance,Male,0.857143,95,0.769231
9,110,1.00,IT,Female,1.000000,89,1.000000

In [5]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Load the dataset
df = pd.read_csv("employee_performance.csv")

# Select numerical features
features = ["Age", "Experience", "Salary"]

# Display original dataset
print("Original Dataset:")
display(df[features])

# Create StandardScaler
scaler = StandardScaler()

# Perform Z-score Normalization
df_normalized = df.copy()
df_normalized[features] = scaler.fit_transform(df[features])

# Display normalized dataset
print("Dataset After Z-score Normalization:")
display(df_normalized[features])

# Compare original and normalized values
comparison = pd.DataFrame()

for feature in features:
    comparison[feature + "_Original"] = df[feature]
    comparison[feature + "_Normalized"] = df_normalized[feature]

print("Comparison of Original and Normalized Values:")
display(comparison)

Original Dataset:

   Age  Experience  Salary
0   25           2   35000
1   30           5   45000
2   28           4   40000
3   35           8   60000
4   40          10   55000
5   26           3   38000
6   32           7   50000
7   29           5   42000
8   38          12   65000
9   45          15   70000

Dataset After Z-score Normalization:

        Age  Experience    Salary
0 -1.256105   -1.287534 -1.311558
1 -0.450910   -0.530161 -0.437186
2 -0.772988   -0.782619 -0.874372
3  0.354286    0.227212  0.874372
4  1.159482    0.732127  0.437186
5 -1.095066   -1.035076 -1.049246
6 -0.128831   -0.025246  0.000000
7 -0.611949   -0.530161 -0.699497
8  0.837404    1.237042  1.311558
9  1.964678    1.994415  1.748744

Comparison of Original and Normalized Values:

,Age_Original,Age_Normalized,Experience_Original,Experience_Normalized,Salary_Original,Salary_Normalized
0,25,-1.256105,2,-1.287534,35000,-1.311558
1,30,-0.450910,5,-0.530161,45000,-0.437186
2,28,-0.772988,4,-0.782619,40000,-0.874372
3,35,0.354286,8,0.227212,60000,0.874372
4,40,1.159482,10,0.732127,55000,0.437186
5,26,-1.095066,3,-1.035076,38000,-1.049246
6,32,-0.128831,7,-0.025246,50000,0.000000
7,29,-0.611949,5,-0.530161,42000,-0.699497
8,38,0.837404,12,1.237042,65000,1.311558
9,45,1.964678,15,1.994415,70000,1.748744

In [6]:
import pandas as pd

# Load the dataset
df = pd.read_csv("employee_performance.csv")

# Display original Salary values
print("Original Salary Values:")
display(df[["Salary"]])

# Perform equal-width binning
# Divide Salary into 4 equal-width intervals
df["Salary_Bin"] = pd.cut(
    df["Salary"],
    bins=4,
    labels=["Low", "Medium", "High", "Very High"]
)

# Display the result
print("Salary After Equal-Width Binning:")
display(df[["Salary", "Salary_Bin"]])

# Display the number of employees in each bin
print("Number of Employees in Each Salary Bin:")
print(df["Salary_Bin"].value_counts().sort_index())

Original Salary Values:

   Salary
0   35000
1   45000
2   40000
3   60000
4   55000
5   38000
6   50000
7   42000
8   65000
9   70000

Salary After Equal-Width Binning:

   Salary Salary_Bin
0   35000        Low
1   45000     Medium
2   40000        Low
3   60000       High
4   55000       High
5   38000        Low
6   50000     Medium
7   42000        Low
8   65000  Very High
9   70000  Very High

Number of Employees in Each Salary Bin:
Salary_Bin
Low          4
Medium       2
High         2
Very High    2
Name: count, dtype: int64

In [7]:
import pandas as pd

# Load the dataset
df = pd.read_csv("employee_performance.csv")

# Display original Experience values
print("Original Experience Values:")
display(df[["Experience"]])

# Perform equal-frequency binning
# Divide Experience into 4 groups with approximately equal number of records
df["Experience_Bin"] = pd.qcut(
    df["Experience"],
    q=4,
    labels=["Low", "Medium", "High", "Very High"]
)

# Display the generated bins
print("Experience After Equal-Frequency Binning:")
display(df[["Experience", "Experience_Bin"]])

# Display the number of records in each bin
print("Number of Employees in Each Bin:")
print(df["Experience_Bin"].value_counts().sort_index())

Original Experience Values:

   Experience
0           2
1           5
2           4
3           8
4          10
5           3
6           7
7           5
8          12
9          15

Experience After Equal-Frequency Binning:

   Experience Experience_Bin
0           2            Low
1           5         Medium
2           4            Low
3           8           High
4          10      Very High
5           3            Low
6           7           High
7           5         Medium
8          12      Very High
9          15      Very High

Number of Employees in Each Bin:
Experience_Bin
Low          3
Medium       2
High         2
Very High    3
Name: count, dtype: int64

In [8]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load the dataset
df = pd.read_csv("employee_performance.csv")

# Create Performance category from Performance_Score
df["Performance"] = pd.cut(
    df["Performance_Score"],
    bins=[0, 79, 89, 100],
    labels=["Low", "Medium", "High"]
)

# Create LabelEncoder
encoder = LabelEncoder()

# Encode Department
df["Department_Encoded"] = encoder.fit_transform(df["Department"])

# Encode Performance
df["Performance_Encoded"] = encoder.fit_transform(df["Performance"])

# Display original and encoded values
print("Label Encoded Dataset:")
display(
    df[
        [
            "Department",
            "Department_Encoded",
            "Performance",
            "Performance_Encoded"
        ]
    ]
)

Label Encoded Dataset:

  Department  Department_Encoded Performance  Performance_Encoded
0         IT                   2         Low                    1
1         HR                   1      Medium                    2
2    Finance                   0      Medium                    2
3         IT                   2        High                    0
4         HR                   1      Medium                    2
5    Finance                   0         Low                    1
6         IT                   2        High                    0
7         HR                   1      Medium                    2
8    Finance                   0        High                    0
9         IT                   2      Medium                    2

In [9]:
import pandas as pd

# Load the dataset
df = pd.read_csv("employee_performance.csv")

# Perform One-Hot Encoding on Department
df_encoded = pd.get_dummies(df, columns=["Department"])

# Display the transformed dataset
print("Dataset After One-Hot Encoding:")
display(df_encoded)

Dataset After One-Hot Encoding:

,Employee_ID,Age,Gender,Salary,Performance_Score,Experience,Department_Finance,Department_HR,Department_IT
0,101,25,Male,35000,78,2,False,False,True
1,102,30,Female,45000,85,5,False,True,False
2,103,28,Female,40000,82,4,True,False,False
3,104,35,Male,60000,90,8,False,False,True
4,105,40,Female,55000,88,10,False,True,False
5,106,26,Male,38000,75,3,True,False,False
6,107,32,Male,50000,92,7,False,False,True
7,108,29,Female,42000,80,5,False,True,False
8,109,38,Male,65000,95,12,True,False,False
9,110,45,Female,70000,89,15,False,False,True

In [10]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

# Load the dataset
df = pd.read_csv("employee_performance.csv")

# Create Performance category from Performance_Score
df["Performance"] = pd.cut(
    df["Performance_Score"],
    bins=[0, 79, 89, 100],
    labels=["Low", "Medium", "High"]
)

# Create Ordinal Encoder
encoder = OrdinalEncoder(
    categories=[["Low", "Medium", "High"]]
)

# Perform Ordinal Encoding
df["Performance_Encoded"] = encoder.fit_transform(
    df[["Performance"]]
).astype(int)

# Display original and encoded values
print("Performance Before and After Ordinal Encoding:")
display(
    df[
        [
            "Performance",
            "Performance_Encoded"
        ]
    ]
)

Performance Before and After Ordinal Encoding:

  Performance  Performance_Encoded
0         Low                    0
1      Medium                    1
2      Medium                    1
3        High                    2
4      Medium                    1
5         Low                    0
6        High                    2
7      Medium                    1
8        High                    2
9      Medium                    1

In [11]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Load the dataset
df = pd.read_csv("employee_performance.csv")

# Select numerical attributes
features = [
    "Age",
    "Experience",
    "Salary",
    "Performance_Score"
]

X = df[features]

# Standardize the numerical data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Perform PCA and reduce to 2 principal components
pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

# Create a DataFrame for the transformed feature matrix
pca_df = pd.DataFrame(
    X_pca,
    columns=["Principal_Component_1", "Principal_Component_2"]
)

# Display the transformed feature matrix
print("Transformed Feature Matrix after PCA:")
display(pca_df)

# Display explained variance
print("\nExplained Variance Ratio:")
print(pca.explained_variance_ratio_)

# Display total explained variance
print("\nTotal Explained Variance:")
print(pca.explained_variance_ratio_.sum())

Transformed Feature Matrix after PCA:

   Principal_Component_1  Principal_Component_2
0              -2.528413              -0.048051
1              -0.757323               0.316275
2              -1.499889               0.133354
3               1.091127               0.370756
4               1.384059              -0.354149
5              -2.404382              -0.626627
6               0.412817               0.981284
7              -1.346686              -0.299434
8               2.453938               0.538455
9               3.194752              -1.011863

Explained Variance Ratio:
[0.9078885  0.07855111]

Total Explained Variance:
0.9864396113941154